aeharding/voyager

server.mjs
src/features/auth/authSlice.ts

We don't want the entire payload to be sent to the server with every request.

Add localStorage, remove cookie for token storage

---

package.json
src/features/shared/Markdown.tsx
src/features/shared/markdown/LinkInterceptor.tsx
src/features/shared/markdown/buildCommunityPlugin.tsx
src/features/shared/markdown/customRemarkGfm.tsx
vite.config.ts
yarn.lock

This is very meh, but I'm tired of looking at mdast/unified documentation.

Add support for community handles (e.g. !memes@lemmy.ml)

---

src/features/auth/AppContext.tsx
src/features/comment/Comment.tsx
src/features/comment/CommentTree.tsx
src/features/comment/Comments.tsx
src/features/comment/commentSlice.ts
src/features/feed/Feed.tsx
src/features/shared/sliding/SlidingNestedCommentVote.tsx
src/pages/posts/CommunitiesPage.tsx
src/pages/profile/ProfilePage.tsx
src/pages/shared/UserPage.tsx

Really excited for this one.
- Add highlighted comment in a comment context chain scroll into view
- Fix swipe to collapse not collapsing entire root comment chain
- Add scroll to top of root comment chain upon swipe to collapse

Various scrolling and swiping comment logic fixes

---

README.md
index.html
server.mjs
src/TabbedRoutes.tsx
src/features/auth/Login.tsx
src/helpers/lemmy.ts
src/pages/profile/ProfilePage.tsx

Add custom lemmy server(s) for self hosting

---

src/pages/search/results/SearchCommunitiesPage.tsx

Fixes https://github.com/aeharding/wefwef/issues/76

fix: Add auth to search queries

---

src/TabbedRoutes.tsx
src/features/comment/Comment.tsx
src/features/comment/CommentEllipsis.tsx
src/features/community/MoreActions.tsx
src/features/community/sidebar/Sidebar.tsx
src/features/labels/Vote.tsx
src/features/post/detail/PostDetail.tsx
src/pages/shared/CommunitySidebarPage.tsx
src/theme/variables.css

Resolves #62
Also tweak dark mode text colors (tone 'em down)

Add sidebar

---

index.html
src/TabbedRoutes.tsx
src/features/comment/reply/CommentReply.tsx
src/features/feed/PostCommentFeed.tsx
src/features/labels/links/shared.ts
src/features/post/inFeed/Post.tsx
src/features/post/inFeed/compact/CompactPost.tsx
src/features/post/inFeed/compact/Thumbnail.tsx
src/features/post/inFeed/compact/self.svg
src/features/post/inFeed/large/LargePost.tsx
src/features/post/shared/MoreActions.tsx
src/features/post/shared/VoteButton.tsx
src/features/settings/appearance/PostView.tsx
src/features/settings/appearance/TextSize.tsx
src/features/settings/appearance/appearanceSlice.tsx
src/features/settings/appearance/posts/PostsViewSelection.tsx
src/pages/settings/PostAppearancePage.tsx

Add compact view

---

.eslintrc
.prettierrc
src/helpers/lemmy.ts
src/vite-env.d.ts
vite.config.ts

Revert "Fix issue #124 wrong servers when installed"

---

src/pages/shared/UserPage.tsx

This prevents you from being able to switch accounts in the API is down

Fix API failure causing annoying redirect

---

src/features/labels/Nsfw.tsx
src/features/post/detail/PostDetail.tsx
src/features/post/new/NewPostRoot.tsx

Add support for marking new posts (URL + pics) as NSFW

---

src/features/inbox/messages/Message.tsx

fix: typo in Message.tsx

---

src/features/post/actions/ActionButton.tsx
src/features/post/shared/MoreActions.tsx

feature: add cursor:pointer to post buttons

---

src/features/auth/Login.tsx

Add more login error messages

---

src/features/auth/authSlice.ts
src/features/community/MoreActions.tsx
src/helpers/lemmy.ts

Fix communities with new posts restricted not being handled

---

src/features/comment/CommentExpander.tsx

Use singular "reply" when there is only one

---

src/features/shared/sliding/BaseSlidingVote.tsx

This is an attempt at a fix because it is flakey to reproduce

Fix swipe to upvote upvoting the wrong thing (#194)

---

src/TabbedRoutes.tsx
src/features/user/AsyncProfile.tsx
src/features/user/LoggedOut.tsx
src/pages/inbox/ConversationPage.tsx
src/pages/profile/ProfilePage.tsx
src/pages/profile/UserPage.tsx
src/pages/settings/UpdateAppPage.tsx

Fix bug where logout => login causes tabs to break

---

src/features/post/inFeed/compact/Thumbnail.tsx
src/features/post/inFeed/large/LargePost.tsx

Resolves #231
Should now be pushed to gpu

Fix performance of feed with blurred (NSFW) items

---

src/TabbedRoutes.tsx
src/pages/search/SearchPage.tsx

closes #61 
Implemented using a ref

Double tap search button to start search

---

.vscode/extensions.json
.vscode/settings.json
README.md

Any feedback on this welcome, additions, etc.

chore: Improve recommended VScode developer setup

---

src/features/comment/edit/CommentEdit.tsx
src/features/comment/reply/CommentReply.tsx
src/features/post/new/NewPostRoot.tsx

Fix new post dialog loose work prompt after successful post

---

src/index.css
src/theme/variables.ts

Fix jagged ionicons in safari/webkit browsers (#215)

---

src/index.css

Revert "Fix jagged ionicons in safari/webkit browsers (#215)"

---

package.json
src/features/auth/PageContext.tsx
src/features/comment/CommentEllipsis.tsx
src/features/inbox/messages/Message.tsx
src/features/post/detail/PostDetail.tsx
src/features/post/inFeed/compact/CompactPost.tsx
src/features/post/inFeed/large/LargePost.tsx
src/features/post/shared/MoreActions.tsx
src/features/report/Report.tsx
src/helpers/useDebounceFn.ts
yarn.lock

Add initial reporting (posts, comments, private messages)

---

src/features/search/SearchOptions.tsx

https://github.com/aeharding/wefwef/issues/265
looks like a simple error with the wrong variable used. :)

Fix #265 - Unable to search for remote users

---

src/features/auth/Login.tsx

Quick change to support autofill for password field

Add support for password autofill

---

src/features/community/titleSearch/TitleSearchResults.tsx

Thought it would be easier to just show what I meant. Makes prefixes more important.

Improve title search

---

public/manifest.json

https://stackoverflow.com/a/75710444/1319878

Fix Android PWA appearing with chrome badge

---

.dockerignore
Dockerfile
README.md

* Reduced number of layers by 3
* Moved corepack & network-timeout to common base
* Reduced number of RUN lines in a row
* Remove unnecessary apk update
* Added .dockerignore to streamline build context
* Updated README to include --init (https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals)

Optimize Dockerfile

---

README.md

Hi, I added my instance at the Ecosystem section. I used the format you used for the other instance.

Added new instance wefwef.nohost.network

---

src/features/comment/reply/CommentReply.tsx
src/features/post/new/NewPostText.tsx
src/features/shared/DynamicDismissableModal.tsx
src/features/shared/IonModalAutosizedForOnScreenKeyboard.tsx
src/features/shared/TextareaAutosizedForOnScreenKeyboard.tsx
src/helpers/safari.ts

This is really fragile logic, but I've tried to abstract it to IonModalAutosizedForOnScreenKeyboard to keep it modular at least...
Resolves #75
If anyone wants to test this (android + ios + desktop) I would appreciate it :) Cheers

Fix create comment, edit comment, create post text area being cut off

---

src/features/comment/Comment.tsx
src/features/comment/reply/ItemReplyingTo.tsx
src/features/community/CommunitySummary.tsx
src/features/feed/EndPost.tsx
src/features/inbox/InboxItem.tsx
src/features/inbox/messages/ConversationItem.tsx
src/features/post/detail/PostDetail.tsx
src/features/post/inFeed/compact/Thumbnail.tsx
src/features/post/inFeed/large/LargePost.tsx
src/features/post/new/NewPostRoot.tsx
src/features/post/shared/Embed.tsx
src/features/settings/appearance/TextSize.tsx
src/features/user/LoggedOut.tsx

This is an attempted fix. I believe there's some font size rounding happening GPU<->CPU that makes the text appear to reflow/changes size briefly at times

Fix font size glitching on iOS

---

src/features/auth/authSlice.ts
src/features/inbox/inboxSlice.ts

This is a superior implementation to #354 because it runs coming back from background and every minute - not just on app startup

Fix revoked tokens not logging out user

---

README.md

Hey there, I just changed my instance domain from wefwef to voyager.nohost.network and updated the README accordingly.

Updated wefwef domain to voyager.nohost.network

---

src/helpers/imageCompress.ts

Fix images being rotated incorrectly

---

src/pages/posts/CommunitiesPage.tsx

https://github.com/aeharding/voyager/issues/362

Re-add group communities by letter

---

src/features/post/detail/PostDetail.tsx

Fix post title font size glitching on iOS due to font size rounding

---

src/features/gallery/GalleryPostActions.tsx
src/features/gallery/GalleryProvider.tsx
src/features/post/postSlice.ts
src/features/post/shared/Embed.tsx

Fix: Voting, viewing an image or visiting a URL should set a post as read

---

src/features/inbox/messages/Message.tsx

Fix for issue #359: Correctly showing links in PMs.

---

src/features/comment/CommentEllipsis.tsx
src/features/community/MoreActions.tsx
src/features/post/shared/MoreActions.tsx
src/features/user/UserPageActions.tsx
src/pages/inbox/MarkAllAsReadButton.tsx

Fix action sheet breaking on taps to present before it closes

---

src/features/comment/CommentSort.tsx
src/features/comment/Comments.tsx
src/features/feed/PostCommentFeed.tsx
src/features/feed/PostSort.tsx
src/pages/posts/PostPage.tsx

Turns out @mdecourcy's approach was better ;)

Fix page scrolling to top on login/logout

---

src/features/auth/PageContext.tsx
src/features/comment/CommentEllipsis.tsx
src/features/comment/Comments.tsx
src/features/comment/reply/CommentReply.tsx
src/features/comment/reply/CommentReplyModal.tsx
src/features/post/detail/PostDetail.tsx
src/features/shared/sliding/SlidingNestedCommentVote.tsx
src/features/shared/sliding/SlidingPostVote.tsx

Add new comment append to top

---

src/features/comment/Comment.tsx
src/features/comment/CommentEllipsis.tsx
src/features/comment/CommentTree.tsx
src/features/comment/Comments.tsx
src/features/feed/FeedContext.ts
src/features/post/detail/PostDetail.tsx
src/features/shared/sliding/SlidingNestedCommentVote.tsx
src/helpers/lemmy.ts

Fix hydrating root comment chains

Fix replying to an unhydrated comment chain

---

src/features/community/titleSearch/TitleSearchResults.tsx

Add authorization to community quick switch if available

---

src/features/settings/appearance/TextSize.tsx

Add even larger font size adjustment

---

src/features/comment/CommentTree.tsx

Fix negative number of comment replies

---

src/TabbedRoutes.tsx
src/features/post/postSlice.ts
src/features/settings/general/GeneralSettings.tsx
src/features/settings/general/hiding/DisableMarkingRead.tsx
src/features/settings/general/hiding/HidingSettings.tsx
src/features/settings/general/posts/Posts.tsx
src/features/settings/settingsSlice.tsx
src/pages/settings/HidingSettingsPage.tsx
src/services/db.ts

This is the groundwork for settings to add mark read on scroll, which is what I will be doing next

Add disable marking posts read

---

src/features/feed/Feed.tsx
src/features/feed/FeedScrollObserver.tsx
src/features/post/inFeed/Post.tsx
src/features/settings/general/hiding/HidingSettings.tsx
src/features/settings/general/hiding/MarkReadOnScroll.tsx
src/features/settings/settingsSlice.tsx
src/helpers/useIonViewIsVisible.tsx
src/pages/shared/CommunityPage.tsx
src/pages/shared/SpecialFeedPage.tsx
src/services/db.ts

Add mark posts read on scroll

---

src/features/labels/links/PersonLink.tsx
src/features/settings/appearance/AppearanceSettings.tsx
src/features/settings/appearance/General.tsx
src/features/settings/settingsSlice.tsx
src/services/db.ts

Broken off from #209. Fixes #200.

Add setting to show instance URLs for remote users

---

src/features/auth/authSlice.ts
src/features/comment/CommentEllipsis.tsx

This PR removes the "Select Text" option for deleted / removed comments

Block select text for deleted comments

---

src/features/feed/Feed.tsx
src/features/feed/endItems/EndPost.tsx
src/features/feed/endItems/FeedLoadMoreFailed.tsx
src/features/feed/useFeedOnScroll.tsx
src/pages/shared/SpecialFeedPage.tsx

Fix scrolling stuck after request failure

---

package.json
pnpm-lock.yaml
server.mjs

Should improve first load for new users of PWA

Add compression to express

---

src/features/gallery/PostGalleryImg.tsx
src/features/labels/img/ItemIcon.tsx
src/features/post/inFeed/compact/Thumbnail.tsx
src/helpers/object.ts
src/services/lemmy.ts

Add image thumbnails when possible

---

src/features/gallery/PostGalleryImg.tsx
src/features/labels/img/ItemIcon.tsx
src/features/post/inFeed/compact/Thumbnail.tsx
src/helpers/object.ts
src/services/lemmy.ts

Not really sure why this is happening, so reverting for now. (I cannot reproduce)
https://lemmy.world/post/2365110
Reverts aeharding/voyager#552

Revert "Add image thumbnails when possible"

---

src/features/post/shared/MoreActions.tsx

Fix share url not being thread link in certain circumstances

---

src/features/comment/CommentEllipsis.tsx
src/features/post/shared/MoreActions.tsx

Add confirmation to delete comment

---

src/features/comment/reply/ItemReplyingTo.tsx

Note: This is buggy on Safari because Safari

Add text selection inside comment reply

---

src/App.tsx
src/TabbedRoutes.tsx

Need to move around providers so gallery has access to page context

Fix logged out guard not working from gallery component

---

src/TabbedRoutes.tsx

Fix android back button closing app when gallery is open

---

src/features/comment/CommentMarkdown.tsx
src/features/post/inFeed/compact/Thumbnail.tsx

- Compact view external links
- "Image" links in comments

Fix certain links not opening in in-app browser

---

src/features/labels/img/ItemIcon.tsx
src/helpers/device.ts
src/services/lemmy.ts

Add support for transparent community icons

---

src/features/feed/ConversationsMoreActions.tsx
src/features/user/UserPageActions.tsx
src/features/user/useUserDetails.tsx
src/pages/inbox/ConversationPage.tsx

feat: added action sheet and direct link to profile in chat page

---

android/app/src/main/java/app/vger/voyager/MainActivity.java

Does not affect gesture based OS navigation

Add Android button bar contrast enforce

---

package.json
pnpm-lock.yaml

- Fix swipe back reliability
- Fix swipe back taking too long

Upgrade @ionic/core tweak fork

---

src/features/feed/FeedContext.tsx
src/features/feed/useHidePosts.tsx

This regressed in 1.9.0 performance improvements

Fix hide read posts button

---

android/capacitor.settings.gradle
ios/App/Podfile
ios/App/Podfile.lock
package.json
pnpm-lock.yaml

We can use @capacitor/haptics again once https://github.com/ionic-team/capacitor-plugins/pull/1735 is merged

Fix android haptics

---

src/theme/AppThemes.ts

Make accent colors less saturated and more darker

---

src/App.tsx
src/features/comment/compose/reply/CommentReply.tsx
src/features/post/new/NewPostText.tsx
src/features/post/new/PostEditorRoot.tsx
src/features/shared/DynamicDismissableModal.tsx
src/helpers/useTextRecovery.ts

Add text recovery on app crash

---

android/app/capacitor.build.gradle
android/capacitor.settings.gradle
src/features/comment/Comments.tsx
src/features/comment/JumpFab.tsx
src/features/post/detail/PostDetail.tsx
src/features/settings/general/comments/Comments.tsx
src/features/settings/general/comments/JumpButtonPosition.tsx
src/features/settings/general/comments/ShowJumpButton.tsx
src/features/settings/settingsSlice.tsx
src/helpers/ionic.ts
src/index.css
src/services/db.ts

Add jump button

---

src/features/report/Report.tsx

Fixed in https://github.com/ionic-team/ionic-framework/pull/28020

Remove double event bug workaround

---

src/features/settings/appearance/themes/appTheme/AppTheme.tsx
src/features/settings/appearance/themes/appTheme/AppThemePreview.tsx
src/services/db.ts
src/theme/AppThemes.ts
src/theme/variables.ts

Add Dracula theme

---

android/capacitor.settings.gradle
package.json
pnpm-lock.yaml

v4.1.1 merged in my fix! https://github.com/capacitor-community/app-icon/issues/43

Remove custom capacitor app icon fork

---

src/features/settings/appearance/themes/appTheme/AppTheme.tsx
src/services/db.ts
src/theme/AppThemes.ts

add theme: tangerine

---

src/features/comment/compose/edit/CommentEdit.tsx
src/features/comment/compose/reply/CommentReply.tsx
src/features/comment/compose/shared.tsx
src/features/post/new/NewPostText.tsx

Submits Comment/Post on Ctrl+Enter.
Shall work on mac also, but not tested.
Fixes: https://github.com/aeharding/voyager/issues/340

feat: submit comment/post on ctrl+enter

---

src/features/labels/links/AgeBadge.tsx
src/features/labels/links/PersonLink.tsx
src/features/settings/general/comments/Comments.tsx
src/features/settings/general/comments/HighlightNewAccount.tsx
src/features/settings/settingsSlice.tsx
src/helpers/date.ts
src/services/db.ts

Add new account highlight with setting

---

package.json

This is causing issues with reproducible builds

Remove pro-manifest.json

---

src/index.css

Fix flickering footer from Ionic upgrade

---

src/TabbedRoutes.tsx
src/features/settings/general/comments/DefaultSort.tsx
src/features/settings/general/other/DefaultFeed.tsx
src/features/settings/general/other/Other.tsx
src/features/settings/settingsSlice.tsx
src/features/settings/shared/SettingSelector.tsx
src/features/shared/CommunitySelectorModal.tsx
src/services/db.ts
src/store.tsx

Add custom default open feed

---

src/features/post/inFeed/Post.tsx

Fix post not hiding properly when partially off screen with swipe

---

android/capacitor.settings.gradle
ios/App/Podfile
ios/App/Podfile.lock
package.json
pnpm-lock.yaml

Fix android crash on saving/copying images

---

src/features/community/useCommunityActions.tsx
src/features/labels/links/CommunityLink.tsx

Fix communities on all and local feeds showing as subscribed

---

src/features/shared/sliding/SlidingItem.tsx

Add sticky swipe icons

---

src/features/auth/authSlice.ts
src/features/comment/links/LinkPreview.tsx
src/features/instances/instancesSlice.tsx
src/features/post/postSlice.ts
src/features/resolve/resolveSlice.tsx
src/features/shared/markdown/LinkInterceptor.tsx
src/helpers/toast.ts
src/helpers/useAppToast.ts
src/services/db.ts
src/store.tsx

Add initial resolve object handling

---

src/features/post/postSlice.ts
src/pages/profile/ProfileFeedHiddenPostsPage.tsx
src/services/db.ts

Add option to reset hidden posts

---

src/features/comment/links/CommentLinks.tsx
src/features/comment/links/LinkPreview.tsx
src/features/search/SearchOptions.tsx
src/features/shared/markdown/LinkInterceptor.tsx
src/features/shared/useLemmyUrlHandler.ts
src/helpers/url.ts
src/helpers/useAppNavigation.ts
src/pages/search/SearchPage.tsx
src/pages/settings/RedditDataMigratePage.tsx

Add URL searching, refactor linking, fix crash

---

src/TabbedRoutes.tsx
src/features/community/search/CommunitySearchResults.tsx
src/features/feed/Feed.tsx
src/features/feed/PostCommentFeed.tsx
src/pages/search/results/SearchFeedResultsPage.tsx
src/pages/shared/CommunityPage.tsx
src/pages/shared/FeedContent.tsx

~~TODO: bottom border of community page~~
Resolves #610

Add initial community search implementation

---

package.json
pnpm-lock.yaml
src/features/shared/Video.tsx

- Only play video if mostly on screen
- Progress bar

Add better feed video handling

---

package.json
pnpm-lock.yaml
src/App.tsx
src/AppCrash.tsx

Add error boundary

---

src/features/feed/Feed.tsx
src/features/feed/endItems/EndPost.tsx
src/pages/search/results/SearchFeedResultsPage.tsx
src/pages/shared/CommunityPage.tsx
src/pages/shared/SpecialFeedPage.tsx

Resolves https://github.com/aeharding/voyager/issues/490

Add time-limited sort reminder in feed 

---

src/features/comment/CommentTree.tsx
src/features/comment/Comments.tsx
src/features/post/detail/PostDetail.tsx
src/features/settings/general/comments/Comments.tsx
src/features/settings/general/comments/TapToCollapse.tsx
src/features/settings/settingsSlice.tsx
src/services/db.ts

Add tap to collapse setting (comments, header)

---

vite.config.ts

Fix manifest.json not served after service worker installation

---

src/features/report/Report.tsx

This will serve as a signal to administrators
to let moderators address the report

Add new report option, "Breaks Community Rules"

---

src/features/comment/CommentEllipsis.tsx
src/features/post/detail/Locked.tsx
src/features/post/detail/PostDetail.tsx
src/features/post/shared/MoreActions.tsx
src/features/shared/sliding/BaseSlidingVote.tsx
src/helpers/toastMessages.ts

Add support for thread locked status

---

src/features/comment/Comment.tsx
src/features/comment/CommentTree.tsx
src/helpers/dom.ts

Scroll comment into view if needed

---

src/TabbedRoutes.tsx
src/features/community/list/CommunitiesList.tsx
src/features/settings/general/other/DefaultFeed.tsx
src/helpers/useSupported.ts
src/pages/shared/SpecialFeedPage.tsx
src/services/db.ts

Add modded communities list, add moderator feed

---

src/pages/shared/CommunityPage.tsx

Fix back button vertical alignment

---

src/index.css

Fix overflowing action sheet labels

---

src/helpers/useAppNavigation.ts

Example: https://lemm.ee/post/13150505

Fix double pushing route

---

src/features/comment/CommentEllipsis.tsx
src/features/inbox/InboxItem.tsx
src/features/inbox/InboxItemMoreActions.tsx
src/helpers/useAppNavigation.ts
src/pages/inbox/InboxPage.tsx

Add more actions ellipsis in inbox

---

src/features/shared/AppContent.tsx
src/pages/shared/FeedContent.tsx

Fix pull to refresh

---

src/App.tsx
src/TabbedRoutes.tsx
src/statusTap.ts

Add tap status bar again to restore feed scroll position

---

src/pages/settings/InstallAppPage.tsx

I'm trying my best to keep the PWA install flow for those that want it!

Add native app install guidance

---

index.html

I honestly have no idea why this is happening :(

Fix vite-pwa strange manifest double injection??

---

package.json
pnpm-lock.yaml
src/features/user/Scores.tsx

See: https://github.com/LemmyNet/lemmy/issues/3393#issuecomment-1779400639

Remove karma, use counts instead

---

src/features/feed/Feed.tsx

Add fix for scroll up triggering refresh on Android

---

src/TabbedRoutes.tsx
src/features/comment/Comment.tsx
src/features/comment/CommentExpander.tsx
src/features/comment/CommentTree.tsx
src/features/comment/Comments.tsx
src/features/comment/ContinueThread.tsx
src/features/comment/LoadParentComments.tsx
src/features/post/detail/PostDetail.tsx
src/helpers/lemmy.ts
src/pages/posts/PostPage.tsx

TODO:
- ~~"Load Parent Comments" shouldn't change indentation~~
- ~~cleanup and optimization, reusable calculation logic for depths~~

Add support for highly nested comments

---

android/app/capacitor.build.gradle
ios/App/Podfile
ios/App/Podfile.lock
package.json
pnpm-lock.yaml

This will be used for in-app tips

Add cordova-plugin-purchase

---

src/pages/settings/about/AboutThanksPage.tsx

Add Apollo to thanks page

---

src/helpers/date.ts

Fix invalid account created dates (set in future)

---

src/features/feed/Feed.tsx
src/features/feed/endItems/FetchMore.tsx
src/features/settings/general/posts/InfiniteScrolling.tsx
src/features/settings/general/posts/Posts.tsx
src/features/settings/settingsSlice.tsx
src/services/db.ts

Add option to turn off infinite scrolling

---

capacitor.config.ts
src/App.tsx
src/TabbedRoutes.tsx
src/features/comment/compose/shared.tsx
src/features/shared/DynamicDismissableModal.tsx
src/features/shared/TextareaAutosizedForOnScreenKeyboard.tsx
src/helpers/useKeyboardOpen.ts
src/listeners/androidSafeArea.ts
src/listeners/index.ts
src/listeners/keyboardPageResizer.ts
src/listeners/statusTap.ts

Also fix various other keyboard glitches

Add iOS keyboard auto show on reply

---

package.json
pnpm-lock.yaml

For more, see: https://github.com/ionic-team/ionic-framework/issues/28546

Upgrade ionic to fix bug with showing keyboard on iOS native light mode

---

src/features/post/postSlice.ts
src/features/settings/general/posts/Posts.tsx
src/features/settings/general/posts/UpvoteOnSave.tsx
src/features/settings/settingsSlice.tsx
src/services/db.ts

feat: Upvote on Save

---

src/features/comment/Comment.tsx
src/features/comment/CommentContent.tsx
src/features/comment/CommentEllipsis.tsx
src/features/comment/ModActions.tsx
src/features/comment/commentSlice.ts
src/features/moderation/ModeratableItem.tsx
src/features/moderation/RemovedByBanner.tsx
src/features/moderation/useCanModerate.tsx
src/features/post/detail/PostDetail.tsx
src/features/post/inFeed/compact/CompactPost.tsx
src/features/post/inFeed/large/LargePost.tsx
src/features/post/postSlice.ts
src/features/post/shared/MoreActions.tsx
src/features/post/shared/MoreModAction.tsx
src/features/user/PostContext.tsx
src/helpers/lemmy.ts
src/helpers/toastMessages.ts
src/index.css
src/pages/posts/PostPage.tsx

This is a start of inline comment moderation. It implements:
- Comment removal status for mods
- Remove comment
- Reapprove comment
- Comment Nuke (remove all comments in chain)

Add start of comment moderation

---

src/features/community/MoreActions.tsx
src/features/community/useCommunityActions.tsx

Add share community

---

package.json
pnpm-lock.yaml
src/features/comment/Comments.tsx
src/helpers/virtua.tsx

https://github.com/inokawa/virtua/pull/249

Upgrade Virtua and add indexed item to remove nested div

---

src/AppCrash.tsx
src/helpers/serviceWorker.ts
src/pages/settings/UpdateAppPage.tsx

Fix PWA infinite update on Safari

---

android/app/capacitor.build.gradle
android/capacitor.settings.gradle
disable_in_app_purchases.sh
ios/App/Podfile
ios/App/Podfile.lock
package.json
pnpm-lock.yaml
src/features/tips/inAppPurchase/Tip.tsx
src/features/tips/inAppPurchase/useInAppPurchase.ts

Add tip plugin

---

src/features/comment/compose/reply/ItemReplyingTo.tsx
src/features/comment/compose/shared.tsx
src/features/post/new/NewPostText.tsx
src/helpers/ionic.ts
src/pages/shared/SelectTextModal.tsx

Fix modal swipes interfering with text selection

---

src/features/shared/Markdown.tsx

Fix tables in comments not scrollable

---

src/features/post/detail/PostDetail.tsx

Fix sole body image not showing when post has url media

---

src/TabbedRoutes.tsx
src/features/community/list/CommunitiesListRedirectBootstrapper.tsx
src/pages/posts/CommunitiesPage.tsx
src/services/app.ts

Add ability to always swipe back to communities list

---

src/features/feed/PostSort.tsx
src/features/feed/usePostSort.tsx
src/features/post/postSlice.ts
src/features/settings/general/posts/DefaultSort.tsx
src/features/settings/general/posts/Posts.tsx
src/features/settings/settingsSlice.tsx
src/features/settings/shared/SettingSelector.tsx
src/helpers/array.ts
src/pages/search/results/SearchCommunitiesPage.tsx
src/pages/search/results/SearchFeedResultsPage.tsx
src/pages/shared/CommunityPage.tsx
src/pages/shared/SpecialFeedPage.tsx
src/services/db.ts

Add default post sort

---

src/features/comment/CommentContent.tsx

Prevents forging deletion with markdown. Fixes #400.
<br />
<br />
<br />
<details>
<summary>Old look</summary>
<br />
</details>

Show icon on deleted comments

---

vite.config.ts

Broke with upgrade to ReactMarkdown v9

Add back iOS 15.2 support

---

src/features/settings/shared/SettingSelector.tsx
src/pages/settings/RedditDataMigratePage.tsx

This probably changed with Ionic upgrade

Fix settings menu item text ellipse

---

src/features/community/list/CommunitiesList.tsx
src/features/community/list/useShowModeratorFeed.ts
src/features/community/titleSearch/TitleSearchResults.tsx

Add moderator feed to quick switcher

---

package.json
pnpm-lock.yaml
src/features/auth/Account.tsx
src/features/auth/AccountSwitcher.tsx
src/features/auth/PageContext.tsx
src/features/comment/compose/reply/CommentReply.tsx
src/features/comment/compose/shared.tsx

Add commenting with other account

---

android/capacitor.settings.gradle
ios/App/Podfile
ios/App/Podfile.lock
package.json
pnpm-lock.yaml

Fix iOS biometric lockout bypassing app lock

---

src/features/feed/PageTypeContext.tsx
src/features/feed/PostCommentFeed.tsx
src/features/gallery/GalleryImg.tsx
src/features/gallery/GalleryProvider.tsx
src/features/post/detail/PostDetail.tsx
src/features/post/inFeed/Post.tsx
src/features/post/inFeed/compact/Thumbnail.tsx
src/features/post/postSlice.ts
src/features/post/shared/Embed.tsx
src/pages/shared/CommunityPage.tsx
src/pages/shared/SpecialFeedPage.tsx

Fix posts being autohidden when opened from community with autohide in community = true

---

src/features/community/list/CommunitiesListRedirectBootstrapper.tsx
src/features/community/list/InitialPageRedirectBootstrapper.tsx
src/features/inbox/BoxesRedirectBootstrapper.tsx
src/pages/inbox/BoxesPage.tsx
src/pages/posts/CommunitiesPage.tsx

Add redirect so tapping inbox tab defaults to open "Inbox (all)"

---

src/GlobalStyles.tsx

Thanks to capacitor team for fixing this:
https://github.com/ionic-team/capacitor-plugins/issues/1905

Add controlled keyboard style depending on app theme

---

src/features/comment/compose/edit/CommentEdit.tsx
src/features/comment/compose/reply/CommentReply.tsx
src/features/post/new/PostEditorRoot.tsx

https://lemmy.world/post/9685829

Fix post and comment editor button styles

---

src/features/auth/authSlice.ts

https://lemmy.world/post/9719007

Fix long passwords not working in Voyager

---

src/features/inbox/inboxSlice.ts

This logic is being temporarily removed because it is functioning incorrectly in Lemmy:
https://github.com/LemmyNet/lemmy/issues/4319

Remove auto logout on detecting invalid token

---

package.json
pnpm-lock.yaml
src/features/comment/Comments.tsx
src/features/feed/Feed.tsx

Upgrade virtua

---

src/pages/inbox/InboxPage.tsx
src/theme/variables.ts

Improve unread inbox item colors, add count to title

---

src/App.tsx
src/features/auth/PageContext.tsx
src/features/instances/instancesSlice.tsx
src/features/post/crosspost/CompactCrosspost.tsx
src/features/post/crosspost/Crosspost.tsx
src/features/post/crosspost/CrosspostContainer.tsx
src/features/post/crosspost/create/CreateCrosspostDialog.tsx
src/features/post/detail/PostHeader.tsx
src/features/post/inFeed/compact/CompactPost.tsx
src/features/post/inFeed/large/LargePost.tsx
src/features/post/new/PostEditorRoot.tsx
src/features/post/shared/MoreActions.tsx
src/features/tips/TipDialog.tsx
src/helpers/FloatingDialog.tsx
src/helpers/lemmy.ts
src/helpers/markdown.ts
src/helpers/routes.ts
src/index.css
src/theme/variables.ts

Add crosspost creation

---

src/features/community/MoreActions.tsx
src/index.scss

Fix android action sheet padding

---

src/features/comment/Comment.tsx
src/features/labels/Vote.tsx

Increase tap target of comment vote buttons

---

src/features/post/crosspost/create/CreateCrosspostDialog.tsx
src/features/post/new/PostEditorRoot.tsx

Add support for autofilling crosspost title

---

src/features/comment/links/LinkPreview.tsx
src/features/gallery/PostMedia.tsx
src/features/post/detail/PostHeader.tsx
src/features/post/inFeed/compact/Thumbnail.tsx
src/features/post/inFeed/large/LargePostContents.tsx
src/features/post/new/PostEditorRoot.tsx
src/features/shared/MarkdownImg.tsx
src/helpers/url.ts

Also add support for jxl extension

Fix media with query parameters showing as link

---

package.json
pnpm-lock.yaml
src/features/comment/links/CommentLinks.tsx
src/features/shared/Markdown.tsx
src/features/shared/markdown/customRemarkGfm.tsx

Fix non-lemmy group mentions, such as a.gup.pe

---

src/Auth.tsx
src/TabbedRoutes.tsx
src/features/auth/login/join/Captcha.tsx
src/features/auth/siteSlice.ts
src/features/comment/Comment.tsx
src/features/comment/CommentEllipsis.tsx
src/features/comment/Comments.tsx
src/features/comment/inFeed/FeedComment.tsx
src/features/comment/useCommentActions.ts
src/features/community/useFetchCommunity.ts
src/features/feed/PostCommentFeed.tsx
src/features/inbox/InboxItemMoreActions.tsx
src/features/moderation/banner/ModeratableItemBanner.tsx
src/features/moderation/useCanModerate.tsx
src/features/moderation/useCommentModActions.tsx
src/features/moderation/useIsAdmin.tsx
src/features/moderation/usePostModActions.tsx
src/features/post/inFeed/Post.tsx
src/features/post/inFeed/compact/CompactPost.tsx
src/features/post/inFeed/large/LargePost.tsx
src/features/post/shared/usePostActions.tsx
src/features/report/Report.tsx
src/features/shared/DynamicDismissableModal.tsx
src/features/shared/Video.tsx
src/features/user/useUserDetails.tsx
src/helpers/lemmy.ts
src/pages/shared/CommentsPage.tsx
src/pages/shared/ModqueuePage.tsx

- bottom sheet presentations
- useImperativeHandle
- replace prop drilling communityName/modqueue with context

Optimize and refactor various components

---

src/features/post/inFeed/compact/Thumbnail.tsx
src/features/settings/appearance/CompactSettings.tsx
src/features/settings/settingsSlice.tsx
src/services/db.ts

Add setting to hide self post thumbnails

---

src/features/shared/useNativeBrowser.ts
src/listeners/statusTap.ts

Fix feed scrolling to top when tapping webview status bar

---

src/features/comment/compose/shared.tsx

Fix android spell check

---

src/core/App.tsx
src/core/AppCrash.tsx
src/features/auth/login/LoginModal.tsx
src/features/auth/login/pickJoinServer/PickJoinServer.tsx
src/features/media/gallery/GalleryMedia.tsx
src/features/media/gallery/GalleryProvider.tsx
src/features/media/gallery/PostMedia.tsx
src/features/media/video/Player.tsx
src/features/media/video/Video.tsx
src/features/post/inFeed/large/useMediaLoadObserver.ts
src/features/post/shared/VoteButton.tsx
src/features/settings/app-icon/AppIcon.tsx
src/features/settings/appearance/themes/appTheme/AppTheme.tsx
src/features/settings/appearance/themes/appTheme/AppThemePreview.tsx
src/features/settings/appearance/themes/system/SelectDeviceMode.tsx
src/features/settings/appearance/themes/system/UserDarkMode.tsx

- Move AppCrash to app root to catch modal (and any other) crashes
- Improve media ref types
- Fix legacy ionic radio syntax

(chore) Misc refactor, crash should always show message

---

src/features/auth/AccountSwitcher.tsx
src/features/auth/PageContext.tsx
src/features/share/asImage/ShareAsImageModal.tsx
src/features/shared/markdown/editing/modes/DefaultMode.tsx
src/routes/pages/settings/SettingsPage.tsx

This will be needed once https://github.com/ionic-team/ionic-framework/pull/29058 is merged

(chore) Fix types for useIonModal

---

src/features/settings/root/DatabaseErrorItem.tsx
src/features/settings/settingsSlice.tsx
src/routes/TabBar.tsx
src/routes/pages/settings/SettingsPage.tsx

Add indexedDB unavailable messaging

---

package.json
pnpm-lock.yaml

There is some behavior changes I am sorting out in Virtua 0.27

Lower Virtua version for now

---

src/features/labels/links/PersonLink.tsx

Add long press to block user

---

src/features/migrate/MigrateList.tsx
src/features/settings/appearance/themes/system/DeviceMode.tsx
src/features/settings/blocks/FilteredKeywords.tsx
src/features/settings/general/posts/DefaultSort.tsx
src/features/settings/general/posts/Posts.tsx
src/features/settings/gestures/SwipeSettings.tsx
src/features/settings/shared/SettingSelector.tsx
src/routes/pages/settings/SettingsPage.tsx

- Some Ionic upgrade layout breaks
- Make some ion-item into buttons
- Cleanup lines on gestures page
- Cleanup gesture page reset sheet
- Type fixup

Refactor and cleanup settings

---

src/core/globalCssOverrides.ts
src/features/media/gallery/GalleryMoreActions.tsx
src/features/media/gallery/GalleryPostActions.tsx
src/features/media/gallery/GalleryProvider.tsx
src/features/media/gallery/ImageMoreActions.tsx
src/helpers/toastMessages.ts

Add share/save/copy image from markdown image preview

---

package.json
pnpm-lock.yaml
src/features/auth/login/join/Legal.tsx
src/features/auth/login/join/Question.tsx
src/features/comment/Comment.tsx
src/features/comment/CommentContent.tsx
src/features/comment/CommentMarkdown.tsx
src/features/comment/links/CommentLinks.tsx
src/features/inbox/InboxItem.tsx
src/features/inbox/messages/Message.tsx
src/features/post/detail/PostHeader.tsx
src/features/shared/markdown/Markdown.tsx
src/features/shared/markdown/components/Table.tsx
src/features/shared/markdown/components/spoiler/Details.tsx
src/features/shared/markdown/components/spoiler/Summary.tsx
src/features/shared/markdown/components/spoiler/spoilerSlice.ts
src/features/shared/markdown/editing/PreviewModal.tsx
src/features/shared/markdown/spoilerRehype.ts
src/features/sidebar/internal/CommunitySidebar.tsx
src/features/sidebar/internal/GenericSidebar.tsx
src/features/sidebar/internal/InstanceSidebar.tsx
src/store.tsx

Add support for lemmy markdown spoilers

---

src/features/shared/AppHeader.tsx

Fix theme being toggled when long press within header textbox

---

src/features/shared/sliding/BaseSlidingVote.tsx
src/helpers/toastMessages.ts

Fix user being able to reply to removed/deleted comment

---

package.json
pnpm-lock.yaml
src/features/shared/markdown/Markdown.tsx

This fixes some edge cases in super sub parsing

Replace supersub markdown plugin with custom for lemmy

---

src/features/community/communitySlice.ts
src/features/community/list/InitialPageRedirectBootstrapper.tsx
src/features/community/useGetRandomCommunity.ts
src/features/feed/Feed.tsx
src/features/search/EmptySearch.tsx
src/features/search/RandomCommunity.tsx
src/features/search/TrendingCommunities.tsx
src/features/shared/markdown/Markdown.tsx
src/features/user/AsyncProfile.tsx
src/helpers/ionic.ts
src/helpers/toastMessages.ts
src/routes/pages/search/RandomCommunityPage.tsx
src/routes/pages/search/SearchPage.tsx
src/routes/pages/settings/SettingsPage.tsx
src/routes/pages/shared/CommunityPage.tsx
src/routes/tabs/profile.tsx
src/routes/tabs/search.tsx
src/routes/tabs/settings.tsx

Add random community button

---

android/app/capacitor.build.gradle
android/capacitor.settings.gradle
ios/App/Podfile
ios/App/Podfile.lock
package.json
pnpm-lock.yaml
src/features/settings/general/other/ClearCache.tsx
src/features/settings/general/other/Other.tsx
src/helpers/toastMessages.ts

Add iOS cache clearing

---

src/features/share/asImage/ShareAsImage.tsx

Hide include post text button if no post body

---

android/app/src/main/AndroidManifest.xml
src/core/App.tsx
src/core/listeners/AppUrlListener.tsx

Add initial deep link implementation

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/app/vger/voyager/MainActivity.java
android/app/src/main/res/values/strings.xml
ios/App/App.xcodeproj/project.pbxproj
ios/App/VoyagerActionExtension/ActionRequestHandler.swift
src/helpers/toastMessages.ts

- open in voyager to share sheet
- add common lemmy instances
- reduce ios share sheet version requirements

Improve android deep linking

---

android/app/src/main/AndroidManifest.xml

https://lemmy.world/post/13032438

Fix * host intent filter causing issues on some android apps

---

package.json
pnpm-lock.yaml
src/features/shared/markdown/editing/Editor.tsx
src/features/shared/markdown/editing/modes/DefaultMode.tsx
src/features/shared/markdown/editing/modes/autocomplete/GenericAutocompleteMode.tsx
src/helpers/dom.ts
src/helpers/markdown.ts
src/helpers/string.ts

- Preserve HTML on paste (convert to md)
- Preserve markdown on quote
- Preserve textarea undo stack by using execCommand
- Misc cleanup

Improve markdown editor

---

android/app/src/main/AndroidManifest.xml

https://stackoverflow.com/a/27238892/1319878

Fix app reset on external android keyboard added/removed

---

src/features/community/CommunitySummary.tsx

Fix reload on subscribe to community search result

---

src/features/shared/markdown/editing/modes/DefaultMode.tsx

Add markdown toolbar support for spoilers, code, hr

---

src/features/labels/Handle.tsx
src/features/labels/links/CommunityLink.tsx
src/features/labels/links/PersonLink.tsx
src/features/labels/links/shared.ts
src/features/post/inFeed/large/LargePost.tsx

Make instance not tappable in large feed view

---

src/core/Auth.tsx
src/features/auth/login/login/Login.tsx
src/features/auth/login/login/Totp.tsx
src/features/comment/compose/reply/CommentReply.tsx
src/features/comment/useCommentActions.ts
src/features/inbox/inboxSlice.ts
src/features/labels/Vote.tsx
src/features/post/postSlice.ts
src/features/post/shared/VoteButton.tsx
src/features/post/shared/usePostActions.tsx
src/features/report/Report.tsx
src/features/resolve/resolveSlice.tsx
src/features/shared/sliding/BaseSlidingVote.tsx
src/features/shared/useLemmyUrlHandler.ts
src/features/user/AsyncProfile.tsx
src/helpers/lemmy.ts
src/helpers/lemmyErrors.ts
src/helpers/toastMessages.ts
src/routes/pages/inbox/ComposeButton.tsx
src/routes/pages/search/results/SearchCommunitiesPage.tsx

Refactor error toast messages

---

android/app/src/main/java/app/vger/voyager/MainActivity.java
src/core/listeners/index.ts
src/core/listeners/ionActivatable.ts
src/core/theme/variables.ts
src/features/comment/Comment.tsx
src/features/inbox/InboxItem.tsx
src/features/labels/Edited.tsx
src/features/labels/Vote.tsx
src/features/post/inFeed/Post.tsx

Add activatable item effect to posts/comments/inbox

---

src/routes/common/Router.tsx
src/routes/tabs/general.tsx
src/routes/tabs/posts.tsx

- Fix blank screen loading home/all/local on non-post tab
- Cleanup of memory router instantiation

Fix routing bugs

---

src/features/post/detail/PostHeader.tsx
src/features/shared/markdown/Markdown.tsx
src/features/shared/markdown/components/Table.tsx

Improve image support in tables

---

src/features/post/crosspost/CrosspostContainer.tsx
src/features/shared/markdown/LinkInterceptor.tsx
src/features/shared/useLemmyUrlHandler.ts

This can help with new instances

Force crossposts to be resolved as lemmy links

---

android/app/src/main/AndroidManifest.xml
src/features/auth/login/data/servers.ts
src/features/community/list/GuestCommunitiesList.tsx

- beehaw.org is not upgrading to 0.19 (and Voyager doesn't support 0.18 anymore)
- removed some non-lemmy instances
- fixed typos

Update join/login instance list

---

.dockerignore
Dockerfile

Docker: copy only the files required for build

---

src/routes/TabBar.tsx
src/routes/tabs/buttons/shared.tsx

Improve tab bar styles with landscape phones

---

src/features/labels/Edited.tsx
src/features/labels/Vote.tsx
src/features/post/detail/Stat.tsx
src/features/post/detail/Stats.tsx
src/features/post/detail/TimeStat.tsx
src/features/post/inFeed/PreviewStats.tsx

Refactor stats into separate component

---

src/features/comment/CommentLinks.tsx
src/features/post/link/Link.tsx
src/features/post/link/LinkPreview.tsx
src/features/shared/InAppExternalLink.tsx
src/features/shared/useLemmyUrlHandler.ts
src/helpers/url.ts

Resolves #1424 (by fixing support instead of removing)

Add mailto link support

---

src/features/inbox/InboxItem.tsx
src/features/labels/links/CommunityLink.tsx

Add ability to tap (and hold) user & community in inbox item footer

---

src/features/inbox/VoteArrow.tsx

Fix vote theme for inbox

---

src/features/post/inFeed/compact/CompactPost.tsx
src/features/post/inFeed/large/LargePost.tsx
src/features/settings/appearance/posts/AlwaysShowAuthor.tsx
src/features/settings/appearance/posts/Posts.tsx
src/features/settings/settingsSlice.tsx
src/services/db.ts

Add always show author in feed

---

package.json
pnpm-lock.yaml
src/features/comment/CommentMarkdown.tsx
src/features/shared/markdown/Markdown.tsx

https://github.com/remarkjs/react-markdown/issues/791

Downgrade rehype-highlight for memory leak

---

src/features/auth/login/data/servers.ts

Add lemmy.myserv.one to login list

---

src/features/shared/markdown/Markdown.tsx

Fix crash with unknown code language

---

src/routes/pages/inbox/ComposeButton.tsx

Fix cancel button on compose new private message alert

---

src/features/feed/PostSort.tsx
src/features/settings/general/comments/DefaultSort.tsx
src/features/settings/general/posts/DefaultSort.tsx

Add default sort label (comment vs post) to action sheet

---

src/features/community/MoreActions.tsx
src/features/feed/SpecialFeedMoreActions.tsx
src/features/feed/helpers.ts
src/features/feed/sort/feedSortSlice.tsx
src/features/feed/sort/useFeedSort.tsx
src/features/post/appearance/PostAppearanceProvider.tsx
src/features/post/appearance/appearanceSlice.ts
src/features/post/inFeed/Post.tsx
src/features/settings/appearance/posts/Posts.tsx
src/features/settings/appearance/posts/RememberType.tsx
src/features/settings/settingsSlice.tsx
src/routes/pages/posts/PostPage.tsx
src/routes/pages/search/results/SearchCommunitiesPage.tsx
src/routes/pages/search/results/SearchFeedResultsPage.tsx
src/routes/pages/shared/CommunityPage.tsx
src/routes/pages/shared/SpecialFeedPage.tsx
src/services/db.ts
src/store.tsx

Still need to cleanup FeedSortFeed thingy and other reused functions/helpers b/t useFeedSort

Add post appearance by community

---

src/features/media/gallery/Media.tsx
src/features/post/inFeed/compact/CompactFeedPostMedia.tsx
src/features/post/inFeed/large/media/LargeFeedPostMedia.tsx
src/features/post/inFeed/usePostSrc.ts

Add fallback post src logic

---

src/features/community/list/CommunityListItem.tsx
src/features/community/list/ResolvedCommunitiesList.tsx
src/features/community/useCommunityActions.tsx
src/helpers/toastMessages.ts

Add swipe to unsubscribe, unfavorite

---

src/services/redgifs.ts

Fix crash on redgifs token refresh

---

src/features/auth/Account.tsx
src/features/auth/AccountSwitcher.tsx
src/features/settings/blocks/BlockedCommunities.tsx
src/features/settings/blocks/BlockedInstances.tsx
src/features/settings/blocks/BlockedUsers.tsx
src/features/settings/blocks/FilteredKeywords.tsx
src/features/shared/ListEditor.tsx
src/routes/pages/settings/BlocksSettingsPage.tsx

Refactor edit button to reusable component, use for Accounts list

Add edit button to filters & blocks page

---

src/features/inbox/InboxItem.tsx

Fix inbox notification truncation

---

src/features/sidebar/internal/CommunitySidebar.tsx
src/features/sidebar/internal/GenericSidebar.tsx
src/features/sidebar/internal/InstanceSidebar.tsx
src/routes/pages/shared/CommunitySidebarPage.tsx
src/routes/pages/shared/InstanceSidebarPage.tsx

Add pull to refresh for sidebar contents

---

src/core/Auth.tsx
src/features/inbox/inboxSlice.ts

Lemmy has a bug where it will sometimes say token is invalid even when it's not.

Remove autologout logic

---

src/core/globalCssOverrides.ts
src/core/theme/AppThemes.ts
src/core/theme/variables.ts
src/features/comment/CommentHeader.tsx
src/features/comment/compose/reply/ItemReplyingTo.tsx
src/features/settings/appearance/themes/appTheme/AppTheme.tsx
src/features/shared/markdown/editing/Editor.tsx
src/services/db.ts

Add sunset theme

---

src/features/community/list/ResolvedCommunitiesList.tsx
src/features/feed/ListingType.tsx
src/features/search/EmptySearch.tsx
src/features/search/SpecialSearchMenu.tsx
src/routes/pages/search/CommunitiesResultsPage.tsx
src/routes/pages/search/results/SearchCommunitiesPage.tsx
src/routes/tabs/search.tsx

Add filter to commmunity search results page

Add explore communities page

---

src/helpers/gif.ts
src/helpers/imageCompress.ts

Fix large animated GIFs being converted to JPEG

---

src/features/media/gallery/Media.tsx
src/features/post/useIsPostUrlMedia.ts
src/helpers/url.ts

Fix certain post videos displaying as images

---

src/features/post/crosspost/create/CreateCrosspostDialog.tsx

Fix overflow on create crosspost community selector

---

src/features/feed/PostCommentFeed.tsx
src/features/settings/blocks/FilteredWebsites.tsx
src/features/settings/settingsSlice.tsx
src/features/user/Profile.tsx
src/helpers/lemmy.test.ts
src/helpers/lemmy.ts
src/routes/pages/profile/ProfileFeedHiddenPostsPage.tsx
src/routes/pages/profile/ProfileFeedItemsPage.tsx
src/routes/pages/search/results/SearchFeedResultsPage.tsx
src/routes/pages/settings/BlocksSettingsPage.tsx
src/routes/pages/shared/ModqueuePage.tsx
src/services/db.ts
src/store.tsx

Add filtered websites

---

src/features/shared/markdown/Markdown.tsx
src/features/shared/markdown/components/spoiler/Details.tsx

Fix large numbered lists cut off in spoiler tags

---

src/features/comment/CommentLinks.tsx

Fix invalid link preview

---

src/features/moderation/ban/BanUser.tsx

Fix user ban with expiration

---

vite.config.ts

https://github.com/Anber/wyw-in-js/issues/62

(chore) Ignore harmless wyw-in-js issues

---

android/app/build.gradle

Disable Google 💩 that breaks reproducible builds

---

src/helpers/markdown.test.ts
src/helpers/markdown.ts

Fix lone body image handling with emoji word in title

---

package.json
pnpm-lock.yaml
src/features/auth/siteSlice.ts

Related: https://github.com/aeharding/voyager/issues/1683

(chore) Upgrade lemmy-js-client

---

src/features/community/useGetRandomCommunity.ts
src/helpers/useSupported.ts

Note: This may have not made it into 0.19.6,
might have to change to 0.20.0
https://github.com/LemmyNet/lemmy/issues/5183

Fix random community behavior in newer lemmy versions

---

package.json
pnpm-lock.yaml
src/core/GlobalStyles.tsx
src/features/settings/settingsSlice.tsx
src/features/settings/syncStorage.ts
src/services/db.ts
src/store.tsx

Improve app startup speed

---

scripts/prebuild.sh

Fixes #1703
verified that it works in CI: https://github.com/aeharding/voyager/actions/runs/11805078576/job/32886733829?pr=1704#step:7:706

fix(docker): pre-build script

---

.github/workflows/build_release.yml
.github/workflows/release.yml
.vscode/extensions.json
fastlane/Fastfile
src/core/AppCrash.tsx
src/routes/pages/settings/about/AppDetails.tsx
src/vite-env.d.ts
vite.config.ts

additional ci work included
resolves: #1708

feat: show app build and release information on about page

---

.github/workflows/build_release.yml
README.md
src/routes/pages/settings/about/AppDetails.tsx

driveby: ci: add beta.vger.app support

ci: beta.vger.app support

---

.github/workflows/build_release.yml

fix: ios dark mode icons not available

---

.github/workflows/build_release.yml

now that we have beta.vger.app :)

ci: always upload s3 artifacts on release

---

.github/workflows/build_release.yml

build: fix f-droid

---

src/features/media/video/Video.tsx

fix: crash when viewing comments with inline videos

---

package.json
pnpm-lock.yaml
vite.config.ts

gonna see if this breaks anything

build: remove css modules patch

---

src/features/comment/CommentHeader.module.css
src/features/community/titleSearch/TitleSearch.module.css
src/features/inbox/InboxItemMoreActions.module.css
src/features/media/video/Player.module.css
src/features/moderation/logs/ModlogItemMoreActions.module.css
src/features/post/crosspost/create/CreateCrosspostDialog.module.css

More info: https://github.com/vitejs/vite/issues/18843

fix: css specificity not working during minification

---

package.json
pnpm-lock.yaml

fixes:
- toast can't always drag to dismiss
- sliding item will stop sliding when moving between sides

chore: upgrade dependencies

---

package.json
patches/@capacitor__android.patch
pnpm-lock.yaml

related: https://github.com/ionic-team/capacitor/issues/7802

fix: development android crash on reinstall

---

src/features/labels/Ago.test.ts
src/features/labels/Ago.tsx
src/features/labels/Edited.tsx
src/features/labels/formatDistanceShort.ts
src/features/user/Scores.tsx

feat: fractional years, improved date duration formatting

---

src/features/comment/CommentLinks.tsx
src/helpers/url.ts

fix: crash with invalid url as link

---

src/features/media/gallery/actions/AltText.tsx
src/features/media/gallery/actions/ImageMoreActions.tsx
src/features/settings/general/GeneralSettings.tsx
src/features/settings/general/media/HideAltText.tsx
src/features/settings/general/media/Media.tsx
src/features/settings/settingsSlice.tsx
src/services/db.ts

feat: setting to hide accessible captions

---

package.json
pnpm-lock.yaml
src/features/media/gallery/GalleryProvider.tsx
src/features/shared/sliding/internal/impl/DMActionsImpl.tsx
src/routes/pages/settings/update/UpdateContext.tsx

~~waiting on es-toolkit release~~

refactor: use asyncNoop

---

src/helpers/number.test.ts
src/helpers/number.ts
src/routes/tabs/buttons/InboxTabButton.tsx

fix: inbox badge count overflow

---

src/features/search/SearchOptions.tsx
src/helpers/appLinkBuilder.ts
src/routes/pages/search/SearchPage.tsx
src/routes/pages/search/results/SearchCommunitiesPage.tsx
src/routes/pages/search/results/SearchFeedResultsPage.tsx

fix: percent character in search causes crash

---

src/features/community/list/ResolvedCommunitiesList.tsx

fix: switching accounts from communities list may crash

---

src/features/search/SearchOptions.tsx

fix: remote user search

---

src/features/feed/PostCommentFeed.tsx
src/features/settings/general/hiding/HidingSettings.tsx
src/features/settings/general/hiding/NeverShowReadPosts.tsx
src/features/settings/settingsSlice.tsx
src/services/db.ts

feat: never show read setting

---

src/features/comment/useCommentActions.ts
src/features/community/useCommunityActions.tsx
src/features/feed/SpecialFeedMoreActions.tsx
src/features/media/gallery/actions/GalleryActions.tsx
src/features/media/gallery/actions/GalleryPostActions.tsx
src/features/post/actions/PostActions.module.css
src/features/post/actions/PostActions.tsx
src/features/post/actions/ShareButton.tsx
src/features/post/actions/useSharePostComment.ts
src/features/post/shared/usePostActions.tsx
src/features/settings/general/other/Other.tsx
src/features/settings/general/other/Share.tsx
src/features/settings/settingsSlice.tsx
src/features/shared/sliding/internal/impl/VotableActionsImpl.tsx
src/features/shared/useSharePostComment.ts
src/helpers/lemmy.ts
src/helpers/share.ts
src/helpers/toastMessages.ts
src/services/db.ts

Default is now sharing from your instance.
This can be configured in settings.
Resolves #1056

feat: customize share instance

---

android/capacitor.settings.gradle
ios/App/Podfile
ios/App/Podfile.lock
package.json
pnpm-lock.yaml

fix: share button missing in in-app android firefox browser

---

src/features/post/inFeed/usePostSrc.ts
src/features/shared/markdown/MarkdownImg.tsx
src/helpers/url.ts

it will still fail if https is not supported,
Voyager requires https inline media

fix: insecure media failing to load

---

.github/workflows/build_release.yml
.github/workflows/ci.yml
.github/workflows/e2e.yml
.github/workflows/release.yml

https://github.com/nodejs/corepack/issues/612

build: fix corepack debacle

---

android/capacitor.settings.gradle
ios/App/Podfile
ios/App/Podfile.lock
package.json
pnpm-lock.yaml

fix: crash when sharing from ipad

---

src/features/post/new/PostEditorRoot.tsx
src/features/shared/markdown/editing/Editor.tsx
src/features/shared/markdown/editing/modes/DefaultMode.tsx
src/features/shared/markdown/editing/uploadImageSlice.tsx
src/features/shared/markdown/editing/useUploadImage.tsx

repro:
1. upload post markdown images
2. upload post image
3. observe post markdown images are deleted

fix: broken post markdown images after uploading post image

---

src/features/auth/login/pickJoinServer/PickJoinServer.tsx

fix: crash during race condition of join instance data reload

---

src/features/labels/Ago.test.ts
src/features/labels/Ago.tsx
src/features/labels/Edited.tsx
src/features/moderation/logs/ModRolePersonLink.module.css
src/features/moderation/logs/ModlogItem.module.css
src/features/moderation/logs/ModlogItem.tsx
src/features/moderation/logs/ModlogItemMoreActions.tsx
src/features/user/Scores.tsx

driveby: fixed negative mod log durations

feat: long press mod log item

---

capacitor.config.ts

This is a hotfix for lemmy.ml blocking some apps

feat: native app user agent

---

capacitor.config.ts

otherwise, user agent polyfills won't work

fix: change to append user agent

---

src/features/post/inFeed/compact/Thumbnail.tsx
src/features/post/link/Link.tsx

previously, they wouldn't load at all

fix: force insecure thumbnail images to load securely

---

src/core/listeners/ionActivatable.ts

this prevents the effect when autoplay gifs is off

fix: ionic tap click effect for canvas and video elements

---

src/features/auth/login/pickJoinServer/PickJoinServer.tsx

workaround for https://github.com/ionic-team/ionic-framework/issues/30279

fix: crash loading join instance selector page

---

ios/App/CapApp-SPM/Package.swift
package.json
pnpm-lock.yaml

needed to add user-agent, otherwise lemmy.ml blocks

fix: downloading images from lemmy.ml on iOS fails

---

src/features/shared/markdown/InlineMarkdown.tsx

fix: quotes in post titles do not appear

---

README.md
src/core/App.tsx
src/features/settings/appearance/themes/system/DeviceMode.tsx
src/features/settings/syncStorage.ts
src/helpers/device.ts
src/services/db.ts

Will maintain device mode on existing installations

feat: default to android device mode on android

---

src/features/share/asImage/ShareAsImage.tsx

fix: share as image from lemmy.ml

---

android/capacitor.settings.gradle
ios/App/CapApp-SPM/Package.swift
package.json
pnpm-lock.yaml

This is a downgrade. Should be reverted when
https://github.com/ionic-team/capacitor-plugins/issues/2337 is fixed, tracked in https://github.com/aeharding/voyager/issues/1934
Resolves #1882

fix: ios split screen

---

src/features/auth/login/data/servers.ts

Also reorganize
Resolves #1452

feat: add lemmy.myserv.one to signup list

---

src/index.tsx

ff tries to restore scroll state and it doesn't work well with dynamic feed content

fix: disable scroll restoration

---

src/features/feed/empty/home/starterPackData.ts

feat: update tech and movies/tv starter packs

---

android/app/src/main/AndroidManifest.xml
src/features/auth/login/data/servers.ts
src/features/feed/empty/home/starterPackData.ts

Due to lemmy.world defederation due to lemmy.one being unmoderated, and only admin hasn't posted in last year.
https://lemmy.world/post/28173093

feat: remove lemmy.one from signup list, community

---

src/core/globalCssOverrides.css
src/features/comment/inTree/Comments.tsx
src/features/post/detail/PostDetail.tsx
src/features/settings/appearance/layout/TwoColumn.tsx
src/features/settings/shared/SettingSelector.tsx
src/routes/pages/posts/PostPage.tsx

also add experimental label, refactor virtual comments mode flag

fix: two column layout pull to refresh on iPad portrait mode

---

src/helpers/useAppNavigation.ts
src/routes/twoColumn/useOpenPostCommentProps.tsx

support for crossposts and user links

feat: posts and comments resolve in second column

---

src/features/auth/login/data/servers.ts

https://lemmy.one/post/27858506

chore: remove lemmy.one instance

---

src/features/labels/Edited.tsx

This matches the new lemmy-ui behavior

feat: edit indicator only shows after 5 minutes

---

package.json
pnpm-lock.yaml

https://github.com/stenciljs/core/pull/6320

fix: downgrade ionic

---

package.json
pnpm-lock.yaml
src/features/auth/siteSlice.ts

Regression from switching to threadiverse

fix: instance downvotes disabled

---

package.json
pnpm-lock.yaml

Accidentally dropped support for 0.19.0-0.19.4 in threadiverse implementation

fix(lemmy): v0.19.3 support

---

package.json
pnpm-lock.yaml

fix(piefed): block users list

---

README.md

https://github.com/orgs/community/discussions/165090#discussioncomment-13671661

docs: fix github breaking height=x on img elements

---

README.md

This reverts commit 5bb357cbd5c03fafd533505c1d7de42ee49dabe7.

docs: revert: fix github breaking height=x on img elements (#2095)

---

src/features/shared/DynamicDismissableModal.tsx

fix: ui glitch after comment editor dismiss

---

package.json
pnpm-lock.yaml

fix(piefed): mark mentions read, save comments, view saved posts/comments
