server.mjs
src/features/auth/authSlice.ts
src/features/community/MoreActions.tsx
src/features/community/communitySlice.ts
src/features/post/new/NewPost.tsx
src/features/post/new/NewPostModal.tsx
src/features/post/new/NewPostRoot.tsx
src/features/post/new/NewPostText.tsx
src/features/post/new/PhotoPreview.tsx
src/pages/shared/CommunityPage.tsx
src/services/lemmy.ts
src/theme/variables.css

Add creating new posts (incl. url or image)

---

src/App.tsx
src/GlobalStyles.tsx
src/TabbedRoutes.tsx
src/features/post/detail/PostDetail.tsx
src/features/post/inFeed/Post.tsx
src/features/settings/appearance/TextSize.tsx
src/features/settings/appearance/appearanceSlice.tsx
src/features/settings/storage.ts
src/features/user/Profile.tsx
src/index.css
src/pages/profile/ProfileFeedItemsPage.tsx
src/pages/settings/AppearancePage.tsx
src/pages/settings/SettingsPage.tsx
src/store.ts

Add appearance page, add font size adjust

---

src/pages/posts/CommunitiesPage.tsx

In Apollo, the community list is sorted alphabetically but also separated by their starting letter. This makes it much clearer and easier to find communities in long lists.
Comparison (Apollo first, Wefwef second):

feat: segregate community list alphabetically

---

src/services/lemmy.ts

Background:
Yesterday, reverse proxied requests on lemmy.app started being rejected from wefwef.app due to rate limiting built into lemmy on lemmy.world due to a sustantial increase in traffic over the last 48 hours.
lemmy.world will shortly enable CORS.
Note: This hotfix may only be deployed to wefwef.app.
Future versions of lemmy will enable CORS * by default like Mastodon, which will completely resolve this issue.

Add emergency hotfix for rejected connections to lemmy.world

---

src/features/post/new/NewPostRoot.tsx

Just a small fix - I noticed that when you make a new post the popup would say "Posted created!".  Updated it to "Post created!".

Typo fix on new post popup

---

src/features/comment/CommentEllipsis.tsx
src/features/feed/SelectTextModal.tsx
src/features/post/shared/MoreActions.tsx
src/index.css
src/pages/shared/SelectTextModal.tsx

Addresses #83 
In Apollo, there's a Select Text button in the ellipsis menu of posts and comments. This update adds similar functionality.
https://github.com/aeharding/wefwef/assets/51917118/c08df094-5d32-4332-ae6d-9b86b7a36e22
Text within this modal has been given a new `selectable` class which sets the default `user-select: none;` to `user-select: text;` to allow selecting the text. It also preserves newlines.

feat: Select text modals

---

.eslintrc
.prettierrc
src/helpers/lemmy.ts
src/vite-env.d.ts
vite.config.ts

Fixes Issue #124 
Defines the `CUSTOM_LEMMY_SERVERS` as a variable through `vite.config.ts`, allowing it to be present after PWA installation.
This requires reading the the environment via Vite's `loadEnv` function, and define the config using a function in order to be able to read the current `mode` (`development`, `production`, `test`).
The `CUSTOM_LEMMY_SERVERS` can be defined in the environment either system wide or through a `.env` file such as `.env.production.local` or `.env.development.local` (the `.local` is not strictly needed, but `.local` files are gitignored).
Sidenote: I added a `.prettierrc` because I use different settings and they were wreaking havoc on the code, this way it should be consistent.

Fix issue #124 wrong servers when installed

---

src/App.tsx
src/GlobalStyles.tsx
src/emotion.d.ts
src/features/comment/Comment.tsx
src/features/comment/reply/CommentReply.tsx
src/features/inbox/messages/Message.tsx
src/features/post/new/NewPostText.tsx
src/features/settings/appearance/DarkMode.tsx
src/features/settings/appearance/UserDarkMode.tsx
src/features/settings/appearance/appearanceSlice.tsx
src/helpers/useDeviceDarkMode.ts
src/helpers/useSystemDarkMode.ts
src/index.css
src/pages/settings/AppearancePage.tsx
src/theme/variables.ts

Adds two toggles to the Settings > Appearance page
1. Whether or not to obey the system value for light/dark mode
2. If user chooses not to use the system value, whether or not to always use dark mode
Code Details:
- Changed CSS to rely on class based dark mode theming rather than media query alone
- Implemented logic to store and update toggle values from settings screen
- Implemented change detection for system dark/light theme if toggle is enabled

feat: Dark mode settings

---

src/features/comment/Comment.tsx
src/features/comment/CommentExpander.tsx
src/features/comment/CommentTree.tsx
src/features/comment/Comments.tsx
src/features/feed/FeedContext.ts
src/features/settings/appearance/CollapsedByDefault.tsx
src/features/settings/appearance/appearanceSlice.tsx
src/helpers/lemmy.ts
src/pages/settings/AppearancePage.tsx

Closes #130 
Probably there is some (or a lot!) of work to do here. Particularly, I would check out the useEffect used in the CommentTree component. Right now I don't have a better idea, so it may be fine but I would check it out twice

Setting to have comments threads collapsed by default

---

src/services/lemmy.ts

1MB is Lemmy's default photo size max https://github.com/LemmyNet/lemmy-ui/issues/1532

Fix maximum files size for uploads

---

server.mjs

These headers help the origin web server identify the original IP that the request came from.
Otherwise, the requests will all appear to come from the wefwef server, which can be problematic for moderation and rate-limiting.
Refs:
* https://github.com/http-party/node-http-proxy#options
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

Pass along X-Forwarded-* headers

---

src/pages/search/SearchPage.tsx

Add clear button to search bar so you can quickly clear text without loosing focus of the search bar. Also change cancel button to be shown when there is some text on the search bar or if the search bar is focused.

Change how search bar is cleared

---

.github/workflows/docker.yml

addresses https://github.com/aeharding/wefwef/issues/253
Like `amd64`, the variant can be left off as `v8` is the default for `arm64`. This should make the GitHub action build something that would work on an M1 laptop (`aarch64` is also normalized to `arm64` by buidkit)

Update docker build to target arm64 rather than arm/v8

---

src/features/shared/markdown/buildCommunityPlugin.tsx

Fixes #73
Fixes an issue causing double-nesting of links. Updates the node transformer to skip transforming link nodes when the parent is of type `link` and has the same URL.

skip parsing links nodes when they are duplicates

---

src/features/comment/Comment.tsx
src/features/post/inFeed/Post.tsx
src/features/post/inFeed/compact/CompactPost.tsx
src/features/post/inFeed/large/LargePost.tsx

**This should not result in any changes for mobile devices.**
Changes for desktop below:
Before:
After:

Fix desktop saved post/comment indicator position

---

src/features/settings/appearance/appearanceSlice.tsx
src/services/db.ts
src/store.ts

This pr moves existing settings to dexie. It also adds support for any combination of user/community specific settings so we can implement some settings in a standard way. Using string keys might look weird but they're fully protected by TS so it's not possible to make a typo with those. Values are also typed per key so should be pretty safe.
Things to test:
- User installing the app for the first time.
- User updating the app from a pre-Dexie version.
- User updating the app from the last version of the DB.
- Regular flow, changing settings, seeing results of those settings
I tested these scenarios and couldn't find any issues but it's better to have another set of eyes check it.

Move settings to Dexie

---

src/features/user/Profile.tsx
src/pages/profile/ProfileFeedItemsPage.tsx

Resolves #283
NOTE: You can technically "swipe" away an item from profile still.
However, in #64 we will have custom profile swipe actions where swipe to hide is not an option on the profile.

Fix posts hidden not appearing on profile

---

src/helpers/useSystemDarkMode.ts

Fixes regression from https://github.com/aeharding/wefwef/pull/74
Application fails to load (blank page) with error `mediaMatch().addEventListener is not a function`.
See also: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#browser_compatibility

Fix safari/ios 13

---

src/features/post/inFeed/compact/CompactPost.tsx

Warning labels exist on large posts, but not on compact posts, so I added them inline to hopefully not increase the size of the compact posts.

Feature: add warning labels to compact posts

---

src/TabbedRoutes.tsx

Fix for issue #323: Clicking the posts button now correctly scrolls to top of the page.

---

src/services/lemmy.ts

Since LemmyNet/lemmy#3421 was merged, Lemmy instances on 0.18.1 and newer allow cross-origin requests.
Notably missing is lemmy.world, which currently is broken as it sends double CORS headers:
```js
> fetch('https://lemmy.world/api/v3/posts/list');
```
> Access to fetch at 'https://lemmy.world/api/v3/posts/list' from origin 'https://wefwef.app' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'https://wefwef.app, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Support bypassing the proxy for some Lemmy instances

---

src/features/auth/authSlice.ts

This is an emergency hotfix related to lemmy.world revoking login tokens.
Without this fix, users will appear logged in but not actually be logged in, since they have an invalid token.

Fix invalidated tokens not being cleared from storage

---

src/pages/search/SearchPage.tsx

Submitting while in the search bar now results in a redirect to the posts list. This was a feature that was present in the old Apollo app that was missing.

Redirecting to posts list on submitting search bar.

---

src/features/feed/PostSort.tsx

Post sort scroll change is working when sort change isn't in the nested top menu.
This PR fixes top > time sort change scroll
Before:
https://youtube.com/shorts/b-EXfg5Q7Ko
after:
https://youtu.be/_idc8nE4Igs

Fix/Scroll to top after top > time selection

---

src/features/post/shared/Embed.tsx
src/features/shared/markdown/LinkInterceptor.tsx

Similar to #226 it allows the web-preview/sharing for both embeds and the markdown links.
Same as the last PR - I don't think this interferes with any existing gestures.
Also helps #69
I wasn't 100% sure if the link interceptor is where you wanted this to be, or if I did it in the style you prefer.
https://github.com/aeharding/wefwef/assets/1349689/975c3492-f721-4af8-bc16-db798369020e

Allow sharing/previewing links and embeds in ios

---

src/GlobalStyles.tsx
src/TabbedRoutes.tsx
src/features/comment/CommentSort.tsx
src/features/comment/Comments.tsx
src/features/feed/Feed.tsx
src/features/feed/PostCommentFeed.tsx
src/features/post/inFeed/Post.tsx
src/features/post/inFeed/compact/CompactPost.tsx
src/features/post/inFeed/compact/Thumbnail.tsx
src/features/post/inFeed/large/LargePost.tsx
src/features/post/shared/Embed.tsx
src/features/settings/appearance/AppearanceSettings.tsx
src/features/settings/appearance/CompactSettings.tsx
src/features/settings/appearance/TextSize.tsx
src/features/settings/appearance/posts/BlurNsfw.tsx
src/features/settings/appearance/posts/PostSize.tsx
src/features/settings/appearance/system/DarkMode.tsx
src/features/settings/appearance/system/UserDarkMode.tsx
src/features/settings/general/GeneralSettings.tsx
src/features/settings/general/comments/CollapsedByDefault.tsx
src/features/settings/general/comments/Comments.tsx
src/features/settings/general/comments/DefaultSort.tsx
src/features/settings/settingsSlice.tsx
src/pages/posts/PostPage.tsx
src/pages/settings/GeneralPage.tsx
src/pages/settings/SettingsPage.tsx
src/services/db.ts
src/store.tsx

Added the ability to set a default sort type for comments in the appearance menu, as it was a personal pet peeve of mine to have comments sorted to hot by default. 
resolves #43

Added default comment sort option.

---

src/features/labels/Nsfw.tsx

The community nsfw doesn't force the post nsfw to be `true`. This results in images from those communities being unblurred, which doesn't match desktop site functionality

[bugfix] all posts in nsfw communities should be nsfw

---

src/features/auth/Account.tsx

Fixes #403
The icon is now the standard size for Ionic for icon-only buttons. It's minutely smaller than before at the normal font size (23.4 x 23.4 vs 24 x 24).

Stop Remove Account icon to be cropped

---

src/features/feed/PostSort.tsx

This pull request enhances the `PostSort` component by adding the currently selected Top interval (e.g. Hour, Week, All Time) in the post sorting menu. When an alternative sort option is selected (e.g. Hot, Most Comments), no interval suffix is displayed.
**Before:**
**After:**

feat: Show selected "Top" interval in post sorting menu

---

src/features/gallery/GalleryPostActions.tsx
src/features/labels/Vote.tsx
src/features/settings/appearance/AppearanceSettings.tsx
src/features/settings/appearance/CompactSettings.tsx
src/features/settings/appearance/General.tsx
src/features/settings/appearance/TextSize.tsx
src/features/settings/appearance/Votes.tsx
src/features/settings/appearance/Voting.tsx
src/features/settings/appearance/posts/BlurNsfw.tsx
src/features/settings/appearance/posts/PostSize.tsx
src/features/settings/appearance/posts/Posts.tsx
src/features/settings/appearance/system/System.tsx
src/features/settings/appearance/system/UserDarkMode.tsx
src/features/settings/blocks/BlockedCommunities.tsx
src/features/settings/blocks/BlockedUsers.tsx
src/features/settings/blocks/FilterNsfw.tsx
src/features/settings/general/comments/CollapsedByDefault.tsx
src/features/settings/general/comments/Comments.tsx
src/features/settings/general/posts/Posts.tsx
src/features/settings/settingsSlice.tsx
src/features/settings/shared/SettingSelector.tsx
src/features/settings/shared/formatting.ts
src/helpers/vote.ts
src/services/db.ts
src/store.tsx

Fixes #170 and fixes #135. When the setting is in the default mode, it should work the same as before.

Allow showing downvotes separately or hiding scores

---

src/services/lemmy.ts

Note: Proxy server is still required due to
https://github.com/LemmyNet/lemmy/issues/3567

Add direct connect by default

---

.dockerignore
Dockerfile

added suggested changes to the docker file from: https://pnpm.io/docker
subsequent builds should now re-use pnpm cache #584
tested after building 1.2, and then 1.3 release:
```
=> [builder 3/5] RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --ignore-scripts 11.6s
```
previously it was 27.1s on the same environment

pnpm optimizations for docker builds

---

README.md

I'm hosting a copy of the Voyager UI, and though it's set to use my instance by default it is up to date and can use any of the other instances too. Would it be appropriate to add my Voyager copy to the Ecosystem portion of the README?

Add my hosted Voyager UI to the Ecosystem

---

.github/workflows/cd.yml

Ionic added WatchOS support to 2023.06

Chore use latest build stack

---

server.mjs
src/features/auth/Login.tsx
src/features/auth/authSlice.ts
src/services/lemmy.ts

NOTE: This just fixes auth for lemmy v0.19.
One month after lemmy v0.19 is released, a new version of Voyager will be released that phases out support for v0.18.
This will allow Voyager to adopt new v0.19 features.
NOTE 2: A new, breaking change of Voyager (Voyager v2) will likely be released sooner than that. Since the native clients can send a custom `Cookie` header, we can upgrade lemmy-js-client sooner than that. The web version will remain stuck of Voyager v1 until most Lemmy servers have a chance to upgrade to v0.19 (one month after v0.19 release)
NOTE3: Phase 2 PR is coming soon.

Add lemmy v0.19 authentication support

---

.github/workflows/ci.yml
src/App.test.tsx
src/features/labels/links/PersonLink.tsx
src/helpers/date.test.ts
src/helpers/date.ts
src/setupTests.ts

feat: cake day 🍰

---

src/features/feed/PostCommentFeed.tsx
src/features/settings/blocks/FilteredKeywords.tsx
src/features/settings/settingsSlice.tsx
src/features/user/Profile.tsx
src/helpers/lemmy.test.ts
src/helpers/lemmy.ts
src/pages/profile/ProfileFeedHiddenPostsPage.tsx
src/pages/profile/ProfileFeedItemsPage.tsx
src/pages/settings/BlocksSettingsPage.tsx
src/services/db.ts
src/store.tsx

Add keyword block

---

src/features/post/new/PostEditorRoot.tsx
src/features/shared/markdown/editing/MarkdownToolbar.tsx

Wasn't able to select some images to use in posts/comments. This change fixes that
Note: looks like lemmy file input uses both `images/*, video/*`, but since uploads are routed through the voyager instance, I am not sure how it would impact it. so I have omitted video/* from this patch

fix some images not being available in the file picker

---

src/features/comment/Url.tsx

Relative URLs need to be thought about more in the future.
Resolves #797

Fix URL parsing crash

---

src/helpers/routes.ts

1. Logout
2. Go to posts tab
3. Go to profile tab
4. Login
5. Immediately switch to posts tab
6. Observe tapping home feed blanks page

Fix bug where tab routes can become invalid

---

src/features/shared/Video.tsx

Resolves #763 (as a workaround. Full fix will need to come from Apple.)

Add hack to fix Safari video element scroll bug

---

src/features/comment/CommentTree.tsx

Previously, all comments were forced to run a render cycle due to this useSelector(). With this fix, the useSelector() will only trigger a render of the comment that was collapsed.
This appears to have a noticeable performance improvement, especially on low-end devices.

Improve performance of comment collapse

---

src/features/settings/gestures/SwipeSettings.tsx
src/features/shared/sliding/BaseSlidingVote.tsx
src/services/db.ts

Adds share gesture for Post, Comment, Inbox
Fixes: https://github.com/aeharding/voyager/issues/696
Currently, there's an intermittent issue described here: https://github.com/aeharding/voyager/issues/696#issuecomment-1686853261

feat: add share gesture

---

src/features/comment/CommentTree.tsx
src/features/settings/gestures/SwipeSettings.tsx
src/features/settings/gestures/gestureSlice.tsx
src/features/shared/sliding/BaseSlidingVote.tsx
src/features/shared/sliding/SlidingItem.tsx
src/services/db.ts

- Rename collapse => collapse to top
Resolves #732

Add collapse comment gesture

---

src/features/community/CommunitySummary.tsx
src/features/community/communitySlice.ts
src/pages/search/results/SearchCommunitiesPage.tsx
src/pages/shared/CommunitySidebarPage.tsx

Resolves #967
Repro:
1. Search community name, don't click on community
2. Go to home/all/local feed, find community
3. Use long press to bring up sidebar. Observe mod list empty

Fix moderators list empty in sidebar edge case

---

src/features/settings/settingsSlice.tsx

Given the large number of images posted on Lemmy in comments, for better or worse, this should probably be enabled by default.

Enable inline images in comments by default

---

src/features/moderation/ModqueueItemActions.tsx
src/features/moderation/useCommentModActions.tsx
src/features/moderation/usePostModActions.tsx
src/helpers/toastMessages.ts

1. A post/comment with a report will only have reports resolved when approved.
2. Introduced concept of restoring post/comment
3. Mod actions list will only have relevant actions, so you cannot double approve
Resolves #983

Fix mod approve/remove/restore post/comment lifecycle

---

src/features/settings/general/hiding/HidingSettings.tsx

I know its a trivial commit but @aeharding you offered us the oppurtunity to do it so here it is.

Update HidingSettings.tsx to remove the double occurance of inside in the helper text of Marking Read/Hiding settings

---

src/TabBar.tsx
src/features/auth/AccountSwitcher.tsx
src/features/auth/PageContext.tsx
src/pages/profile/ProfilePage.tsx

Since #715 has blocked and inactive for a while, and I really miss this feature from Apollo, I thought I'd try my own version of this.
This makes tapping the Profile button in the tab bar pull up the account switcher IF the profile page is already active in the profile tab (and hasn't been scrolled down on).
This means tapping the Profile button TWICE will bring up the account switcher also.
If you open the Profile page by tapping the button once, and then navigate away by clicking one of the links on it, tapping the profile button again will bring you back to the profile page, as before.
https://github.com/aeharding/voyager/assets/98132670/1f41e4db-5917-44bb-ac38-1c94948861b5

feat: Quick account switcher

---

src/features/comment/CommentMarkdown.tsx
src/features/post/detail/PostHeader.tsx
src/features/shared/Markdown.tsx
src/features/shared/Video.tsx

This only worked in iOS incidentally due to a workaround for iOS <= 17.1 having broken video implementation

Fix tap to open video in feed

---

src/features/post/postSlice.ts
src/features/settings/settingsSlice.tsx

Settings will still not persist because iOS disables indexedDB in lockdown mode

Fix posts failing to load in iOS lockdown mode

---

src/features/shared/DynamicDismissableModal.tsx

When pressing "cancel" on a post or comment that has unsaved changes, the button to confirm deletion now says "Discard" instead of "Delete".
This fixes #1059.

Change post/comment editor abort action title to "Discard"

---

src/features/inbox/inboxSlice.ts

Now that Lemmy v0.19.2 was released with the fix, re-adding auto logout functionality.
This reverts commit 0b572088bee6acfca92df49fc6b86769f9a629a2.

Revert "Remove auto logout on detecting invalid token (#1120)"

---

src/features/comment/CommentMarkdown.tsx
src/features/shared/Markdown.tsx
src/features/shared/markdown/editing/PreviewModal.tsx

For example, tapping a user link in the post/comment preview dialog

Fix internally routed preview links navigating underneath preview dialog

---

src/store.tsx

For example, go to /profile logged out, login, tap posts tab

Fix tab switch issue in some scenarios on switching accounts

---

.eslintrc
src/features/auth/login/join/Join.tsx
src/features/auth/login/login/Login.tsx
src/features/auth/login/login/PickLoginServer.tsx
src/features/auth/login/login/Totp.tsx
src/features/auth/login/pickJoinServer/PickJoinServer.tsx
src/features/post/inFeed/Post.tsx
src/features/share/asImage/ShareAsImage.tsx
src/features/shared/IonModalAutosizedForOnScreenKeyboard.tsx
src/listeners/AndroidBackButton.tsx
src/pages/search/SearchPage.tsx
src/pages/shared/CommunityPage.tsx
src/react.d.ts
src/services/nativeFetch.ts
vite.config.ts

Recommended via https://typescript-eslint.io/linting/troubleshooting/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors

Disable eslint no-undef

---

src/features/comment/Comment.tsx
src/features/comment/commentSlice.ts
src/features/comment/inTree/CommentTree.tsx
src/features/settings/general/comments/Comments.tsx
src/features/settings/general/comments/ShowCollapsed.tsx
src/features/settings/settingsSlice.tsx
src/features/shared/sliding/BaseSlidingVote.tsx
src/services/db.ts

Allow showing the content of collapsed comments

---

src/features/shared/sliding/BaseSlidingVote.tsx
src/features/shared/sliding/SlidingItem.tsx
src/helpers/useEvent.ts

Essentially when you sipe an item and you cursor is no longer within the item boundaries, the end event will not be detected

Fix mouse drag swipe actions sometimes getting stuck

---

.dockerignore
.gitignore

When running `tsc --incremental` this file is generated. This can be ignored in git/docker

Ignore Typescript Incremental Cache File

---

playwright.config.ts

If `process.env.CI === true`, Playwright will use `pnpm preview`, otherwise `pnpm dev`.

Update Playwright config to choose the test web server based on env

---

src/features/moderation/logs/ModlogItem.tsx
src/features/moderation/logs/ModlogItemMoreActions.tsx
src/features/moderation/logs/types/addCommunity.ts
src/features/moderation/logs/types/addInstance.ts
src/features/moderation/logs/types/banFromCommunity.ts
src/features/moderation/logs/types/banFromInstance.ts
src/features/moderation/logs/types/featurePost.ts
src/features/moderation/logs/types/hideCommunity.ts
src/features/moderation/logs/types/lockPost.ts
src/features/moderation/logs/types/purgeComment.ts
src/features/moderation/logs/types/purgeCommunity.ts
src/features/moderation/logs/types/purgePerson.ts
src/features/moderation/logs/types/purgePost.ts
src/features/moderation/logs/types/removeComment.ts
src/features/moderation/logs/types/removeCommunity.ts
src/features/moderation/logs/types/removePost.ts
src/features/moderation/logs/types/shared.ts
src/features/moderation/logs/types/transferCommunity.ts
src/features/moderation/useIsAdmin.tsx
src/helpers/array.ts
src/helpers/useAppNavigation.ts

By request, I rebased my old branch for #1046 to hopefully work with the recent code changes.
Had to restore a couple of functions that were removed or changed (`helpers/array.ts#notEmpty()` and `useIsAdmin()` with optional argument). Only tested briefly but seems to work fine.

Revamped modlog with moderation reason

---

package.json
pnpm-lock.yaml
src/features/settings/general/other/BackupSettings.tsx
src/features/settings/general/other/Other.tsx
src/features/settings/general/other/backup/BackupSettings.tsx
src/features/settings/general/other/backup/helpers.ts
src/helpers/object.test.ts
src/helpers/object.ts

Add backup/restore settings

---

src/core/App.tsx
src/features/comment/useCommentActions.ts
src/features/community/MoreActions.tsx
src/features/feed/SpecialFeedMoreActions.tsx
src/features/media/gallery/GalleryMoreActions.tsx
src/features/media/gallery/GalleryPostActions.tsx
src/features/post/actions/PostActions.tsx
src/features/post/shared/usePostActions.tsx
src/features/settings/general/other/backup/helpers.ts
src/features/settings/gestures/SwipeSettings.tsx
src/features/settings/settingsSlice.tsx
src/features/settings/storage.ts
src/features/settings/syncStorage.ts
src/helpers/device.ts
src/routes/pages/settings/InstallAppPage.tsx

Use device mode specific share icon

---

src/features/labels/links/CommunityLink.tsx
src/features/labels/links/PersonLink.tsx
src/features/settings/general/other/Other.tsx
src/features/settings/general/other/SubscribedIcon.tsx
src/features/settings/settingsSlice.tsx
src/features/settings/shared/SettingSelector.tsx
src/routes/pages/shared/SpecialFeedPage.tsx
src/services/db.ts

Add subscribed icon

---

src/features/auth/authSelectors.ts
src/features/auth/login/login/Login.tsx
src/features/comment/CommentLinks.tsx
src/features/feed/SpecialFeedMoreActions.tsx
src/features/shared/markdown/LinkInterceptor.tsx
src/features/shared/useLemmyUrlHandler.ts
src/routes/common/ActorRedirect.tsx
src/services/app.ts
src/services/lemmy.ts

Resolves #1576
Now you can set the following (testing purposes only!):
- `VITE_FORCE_LEMMY_INSECURE=1` to force all lemmy instance connections to http instead of https.
- `VITE_CUSTOM_LEMMY_SERVERS=localhost:3001,localhost:3002` a comma separated list of default lemmy servers. If _config is found it will be preferred.

Improve support for testing (http, custom ports, env variables)

---

.github/workflows/e2e.yml
e2e/ci/docker-compose.yml
e2e/ci/lemmy.hjson
e2e/ci/nginx.conf

Some things I want to highlight or would like opinions/thoughts on.
- The e2e action, as of this commit, will not run on `push` and `pull_request` triggers. It will have to be manually triggered.
- The idea is to ensure that the tests are somewhat stable before adding back these removed triggers. In the meantime, there will be failed runs of the action but they will become increasingly infrequent with time.
- PRs will be fairly frequent for the next few weeks and tests might undergo several changes (and refactors) before they become stable. This will probably involve breaking from this repo's convention of squash merging PRs but I will try to avoid any superfluous commits.
- If you feel there are user stories that should take priority, please let me know.

Update e2e action to use a better testing setup

---

.github/workflows/e2e.yml
src/features/auth/authSelectors.ts
src/features/auth/authSlice.ts

After the user logs in, `state.auth.currentInstance` changes from `<hostname>:<PORT>` to `<hostname>` [1]. Setting `VITE__TEST_MODE=1` will override this behaviour with a couple of small changes and no side-effects. Using this var name because similar overrides might be needed elsewhere in the future and this should cover most (or all) of them.
Also updated the build step in e2e action.
[1]: [Lemmy sets the `iss` claim to hostname](https://github.com/LemmyNet/lemmy/blob/63a686d390e441216718a3d64408336409890791/crates/api_common/src/claims.rs#L48) when creating JWTs. `authSlice.addJwt` updates `state.auth.currentInstance` with the value of this claim.

Override lemmy server URL when 'VITE__TEST_MODE' is set

---

src/features/shared/selectorModals/CommunitySelectorModal.tsx

Change to correct behavior documented @ https://github.com/aeharding/voyager/issues/1652
I chose to use the existing LIMIT constant (50) instead of 20 - but can correct this to exactly match lemmy-ui, if that's preferred.

Update CommunitySelectorModal API query to use global limit

---

src/core/GlobalStyles.tsx
src/core/listeners/AppUrlListener.tsx
src/features/auth/PageContext.tsx
src/features/comment/CommentHeader.tsx
src/features/inbox/InboxItem.tsx
src/features/labels/links/PersonLink.tsx
src/features/post/detail/PostHeader.tsx
src/features/post/inFeed/compact/CompactPost.tsx
src/features/post/inFeed/large/LargePost.tsx
src/features/settings/settingsSlice.tsx
src/features/settings/tags/TagsSettings.tsx
src/features/settings/tags/UserTagsPromo.tsx
src/features/settings/tags/browse/BrowseTags.tsx
src/features/shared/useLemmyUrlHandler.ts
src/features/tags/SourceUrlButton.tsx
src/features/tags/UserTagModal.tsx
src/features/tags/userTagSlice.tsx
src/features/user/usePresentUserActions.ts
src/helpers/useAppNavigation.ts
src/routes/pages/search/SearchPage.tsx
src/services/db.ts

Add final user tags feature work

---

e2e/community-feed.spec.ts
eslint.config.js
package.json
src/features/media/gallery/GalleryProvider.tsx
src/features/shared/markdown/components/spoiler/spoilerSlice.ts
src/services/db.ts
src/vite-env.d.ts
tsconfig.json
vite.config.ts

ci: release build not completing

---

package.json
pnpm-lock.yaml
src/features/shared/markdown/Markdown.tsx

no more memory leaks because highlight.js was released!

chore: upgrade rehype-highlight

---

src/features/auth/login/join/Question.tsx

... because users are typing "lemmy in" and getting denied
https://vger.social/post/12482661

fix: remove application answer placeholder

---

ios/App/App.xcodeproj/project.pbxproj
ios/App/App/Info.plist
src/features/post/new/PhotoPreview.tsx
src/features/post/new/PostEditorRoot.tsx
src/features/shared/markdown/editing/Editor.tsx
src/features/shared/markdown/editing/modes/DefaultMode.tsx
src/features/shared/markdown/editing/useUploadImage.tsx
src/helpers/imageCompress.ts

TODO test larger videos, check mobile capture etc
Resolves #986

feat: video upload

---

src/features/comment/CommentHeader.module.css
src/features/community/titleSearch/TitleSearch.module.css
src/features/inbox/InboxItemMoreActions.module.css
src/features/media/video/Player.module.css
src/features/moderation/logs/ModlogItemMoreActions.module.css
src/features/post/crosspost/create/CreateCrosspostDialog.module.css

This reverts commit b78ff280d11ed54a79f66ec94938f37a2a9904a6.
Workaround was fixed in vite 6.2: https://github.com/vitejs/vite/issues/18843

refactor: revert "fix: css specificity not working during minification (#1756)"

---

package.json
pnpm-lock.yaml
src/features/media/video/OutPortalEventDispatcher.tsx
src/features/media/video/Video.tsx
src/features/media/video/VideoPortalProvider.module.css
src/features/media/video/VideoPortalProvider.tsx

~~Waiting on https://github.com/httptoolkit/react-reverse-portal/pull/45~~

refactor: video portal node inline elements

---

src/features/settings/settingsSlice.tsx

Wait for apps to update over the course of a month before enabling by default

fix: disable go.getvoyager.app by default temporarily
